-- Rework resource-island guardian bosses to a Colossus-style shared-HP, per-player-damage boss.
-- Add the HP pool, status, tier and elemental-defence profile to island_bosses.
ALTER TABLE island_bosses ADD COLUMN tier           integer                  NOT NULL DEFAULT 1;
ALTER TABLE island_bosses ADD COLUMN max_health     bigint                   NOT NULL DEFAULT 0;
ALTER TABLE island_bosses ADD COLUMN current_health bigint                   NOT NULL DEFAULT 0;
ALTER TABLE island_bosses ADD COLUMN status         character varying(16)    NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE island_bosses ADD COLUMN attack_element character varying(8)     NOT NULL DEFAULT 'FIRE';
ALTER TABLE island_bosses ADD COLUMN defense_fire   integer                  NOT NULL DEFAULT 100;
ALTER TABLE island_bosses ADD COLUMN defense_wind   integer                  NOT NULL DEFAULT 100;
ALTER TABLE island_bosses ADD COLUMN defense_earth  integer                  NOT NULL DEFAULT 100;
ALTER TABLE island_bosses ADD COLUMN defense_water  integer                  NOT NULL DEFAULT 100;

-- backfill existing rows so they are immediately fightable (world is typically reseeded anyway)
UPDATE island_bosses SET max_health = 150000 * level, current_health = 150000 * level WHERE max_health = 0;

-- per-player damage tally (mirrors colossus_damage but keyed by player)
CREATE TABLE island_boss_damage (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boss_id            bigint NOT NULL,
    player_id          bigint NOT NULL,
    accumulated_damage bigint NOT NULL DEFAULT 0,
    last_contribution_at timestamp with time zone,
    CONSTRAINT island_boss_damage_uq UNIQUE (boss_id, player_id)
);
CREATE INDEX island_boss_damage_boss_idx ON island_boss_damage (boss_id);

-- marching boss strikes reuse the movement table
ALTER TABLE movements ADD COLUMN target_boss_id bigint;
