-- Phase 2/3: contested resource buildings (per-player garrison, 10-min payout) + alliance tier gate.
-- Per-player garrison is stored in the existing json `garrison` column (now playerId -> unit -> qty).
ALTER TABLE resource_nodes ADD COLUMN last_payout_at timestamp with time zone;
ALTER TABLE resource_nodes ADD COLUMN control_since  timestamp with time zone;

-- Progress an alliance earns IN a tier (counts toward unlocking the NEXT tier for founding/conquest).
CREATE TABLE alliance_tier_progress (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alliance_id     bigint  NOT NULL,
    tier            integer NOT NULL,
    boss_kills      integer NOT NULL DEFAULT 0,
    control_seconds bigint  NOT NULL DEFAULT 0,
    CONSTRAINT alliance_tier_progress_uq UNIQUE (alliance_id, tier)
);

-- Phase 4: alliance crest shown above controlled resource buildings.
ALTER TABLE alliances ADD COLUMN emblem character varying(8) NOT NULL DEFAULT '🛡';

