-- City Groups: per-player, purely-organizational grouping of a player's own cities (UI/navigation
-- only). A city may belong to many groups (many-to-many). Groups are distinguished by a preset icon.

CREATE TABLE city_groups (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_player_id bigint  NOT NULL,
    name            varchar(40)  NOT NULL,
    icon            varchar(8)   NOT NULL DEFAULT '🏰',
    sort_order      integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_city_groups_owner ON city_groups(owner_player_id);

CREATE TABLE city_group_memberships (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_group_id bigint NOT NULL REFERENCES city_groups(id) ON DELETE CASCADE,
    city_id       bigint NOT NULL,
    CONSTRAINT city_group_memberships_uq UNIQUE (city_group_id, city_id)
);
CREATE INDEX idx_cgm_city  ON city_group_memberships(city_id);
CREATE INDEX idx_cgm_group ON city_group_memberships(city_group_id);
