-- Support / reinforcements: foreign troops stationed at a host city to help defend it.
-- One row per (host city, owning player); units keyed by UPPERCASE unit name.
CREATE TABLE public.reinforcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id bigint,
    host_city_id bigint NOT NULL,
    owner_player_id bigint NOT NULL,
    units jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE INDEX idx_reinf_host ON public.reinforcements USING btree (host_city_id);
CREATE INDEX idx_reinf_owner ON public.reinforcements USING btree (owner_player_id);
