-- Replace the per-island Bandit Camp with the account-wide Bandit Tower (100-level PvE climb).

-- Drop the old camp tables. CASCADE removes the movements.target_camp_id FK and the owned sequence.
ALTER TABLE public.movements DROP CONSTRAINT IF EXISTS movements_target_camp_id_fkey;
DROP TABLE IF EXISTS public.bandit_camps CASCADE;
DROP TABLE IF EXISTS public.bandit_camp_levels CASCADE;
-- movements.target_camp_id is left in place (now unused / unconstrained) to avoid rewriting the table.

-- One row per player: their Bandit Tower climb. current_level_defenders holds the live, persistent
-- (possibly-damaged) defending force of the current level — survivors carry across attempts.
CREATE TABLE public.bandit_tower_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id bigint NOT NULL UNIQUE,
    current_level integer NOT NULL DEFAULT 1,
    highest_cleared integer NOT NULL DEFAULT 0,
    current_level_defenders jsonb DEFAULT '{}'::jsonb NOT NULL,
    current_level_initialized boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_bandit_tower_player ON public.bandit_tower_progress USING btree (player_id);
