-- Siege & Conquest: an 8h siege laid on a city by a winning hero-led attack with a Defense ship.

CREATE TABLE public.sieges (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id              bigint NOT NULL,
    city_id               bigint NOT NULL,
    besieging_player_id   bigint NOT NULL,
    besieging_alliance_id bigint,
    origin_city_id        bigint,
    status                varchar(16) NOT NULL DEFAULT 'ACTIVE',
    started_at            timestamptz NOT NULL DEFAULT now(),
    ends_at               timestamptz,
    besieging_troops      json NOT NULL DEFAULT '{}',
    besieging_ships       json NOT NULL DEFAULT '{}',
    hero_id               bigint
);
CREATE INDEX idx_sieges_city   ON public.sieges (city_id);
CREATE INDEX idx_sieges_status ON public.sieges (status);
CREATE INDEX idx_sieges_player ON public.sieges (besieging_player_id);

-- siege-related movement targeting + the siege-attempt flag on an outbound attack
ALTER TABLE public.movements ADD COLUMN target_siege_id bigint;
ALTER TABLE public.movements ADD COLUMN siege_intent    boolean NOT NULL DEFAULT false;

-- a freshly conquered city awaits its new owner's race choice
ALTER TABLE public.cities ADD COLUMN conquered_pending_race boolean NOT NULL DEFAULT false;
