-- (H2) Per-city Library research tree.
create table city_library_research (
  id           bigint generated by default as identity primary key,
  city_id      bigint not null references cities(id),
  research_id  varchar(32) not null,
  status       varchar(16) not null default 'RESEARCHING',
  started_at   timestamp with time zone not null default current_timestamp,
  completes_at timestamp with time zone,
  unique (city_id, research_id)
);
create index idx_clr_city on city_library_research(city_id);
