-- ============================================================
-- POLIS — Rise of the Aegean : initial schema (H2-compatible)
-- ============================================================

create table worlds (
  id          bigint generated by default as identity primary key,
  name        varchar(64) not null,
  speed       int not null default 1,
  created_at  timestamp with time zone not null default current_timestamp
);

create table alliances (
  id          bigint generated by default as identity primary key,
  world_id    bigint not null references worlds(id),
  tag         varchar(8)  not null,
  name        varchar(64) not null,
  leader_id   bigint,
  created_at  timestamp with time zone not null default current_timestamp
);

create table players (
  id            bigint generated by default as identity primary key,
  username      varchar(32)  not null unique,
  email         varchar(128) unique,
  password_hash varchar(100) not null,
  world_id      bigint not null references worlds(id),
  alliance_id   bigint references alliances(id),
  level         int not null default 1,
  combat_points int not null default 0,
  is_npc        boolean not null default false,
  created_at    timestamp with time zone not null default current_timestamp
);
alter table alliances add constraint fk_alliance_leader foreign key(leader_id) references players(id);
create index idx_players_world on players(world_id);

create table islands (
  id        bigint generated by default as identity primary key,
  world_id  bigint not null references worlds(id),
  name      varchar(64) not null,
  ocean_x   int not null,
  ocean_y   int not null,
  px        int not null,
  py        int not null,
  seed      bigint not null
);

create table cities (
  id            bigint generated by default as identity primary key,
  world_id      bigint not null references worlds(id),
  player_id     bigint references players(id),
  island_id     bigint not null references islands(id),
  slot          int not null,
  name          varchar(64) not null,
  is_capital    boolean not null default false,
  god           varchar(16),
  wood          double precision not null default 0,
  stone         double precision not null default 0,
  silver        double precision not null default 0,
  favor         double precision not null default 0,
  power         double precision not null default 0,
  points        int not null default 0,
  last_tick_at  timestamp with time zone not null default current_timestamp,
  created_at    timestamp with time zone not null default current_timestamp,
  version       bigint not null default 0,
  unique (island_id, slot)
);
create index idx_cities_player on cities(player_id);
create index idx_cities_world  on cities(world_id);

create table city_buildings (
  id       bigint generated by default as identity primary key,
  city_id  bigint not null references cities(id) on delete cascade,
  type     varchar(24) not null,
  level    int not null default 0,
  unique (city_id, type)
);

create table city_units (
  id       bigint generated by default as identity primary key,
  city_id  bigint not null references cities(id) on delete cascade,
  type     varchar(24) not null,
  count    int not null default 0,
  unique (city_id, type)
);

create table city_research (
  id       bigint generated by default as identity primary key,
  city_id  bigint not null references cities(id) on delete cascade,
  type     varchar(24) not null,
  unique (city_id, type)
);

create table build_jobs (
  id            bigint generated by default as identity primary key,
  city_id       bigint not null references cities(id) on delete cascade,
  queue_type    varchar(16) not null,
  building_type varchar(24),
  to_level      int,
  unit_type     varchar(24),
  batch         int,
  position      int not null,
  started_at    timestamp with time zone,
  finish_at     timestamp with time zone,
  total_seconds int not null,
  created_at    timestamp with time zone not null default current_timestamp
);
create index idx_jobs_city   on build_jobs(city_id);
create index idx_jobs_finish on build_jobs(finish_at);

create table movements (
  id               bigint generated by default as identity primary key,
  world_id         bigint not null references worlds(id),
  player_id        bigint references players(id),
  source_city_id   bigint references cities(id),
  target_city_id   bigint references cities(id),
  target_island_id bigint references islands(id),
  target_slot      int,
  phase            varchar(16) not null,
  units            json not null default '{}',
  loot             json,
  depart_at        timestamp with time zone not null default current_timestamp,
  arrive_at        timestamp with time zone not null,
  resolved         boolean not null default false
);
create index idx_moves_arrive on movements(arrive_at);
