create table messages (
  id             bigint generated by default as identity primary key,
  from_player_id bigint references players(id),
  to_player_id   bigint references players(id),
  body           varchar(1000) not null,
  sent_at        timestamp with time zone not null default current_timestamp,
  read_flag      boolean not null default false
);
create index idx_msg_to on messages(to_player_id);
