-- (H2-compatible) battle reports

create table battle_reports (
  id                       bigint generated by default as identity primary key,
  world_id                 bigint not null,
  movement_id              bigint,
  fought_at                timestamp with time zone not null default current_timestamp,
  outcome                  varchar(16) not null,

  attacker_player_id       bigint,
  attacker_city_id         bigint,
  attacker_city_name       varchar(128),
  attacker_player_name     varchar(64),

  defender_player_id       bigint,
  defender_city_id         bigint,
  defender_city_name       varchar(128),
  defender_player_name     varchar(64),

  attacker_troops_sent     json not null default '{}',
  attacker_troops_lost     json not null default '{}',
  attacker_troops_survived json not null default '{}',
  defender_troops_present  json not null default '{}',
  defender_troops_lost     json not null default '{}',
  defender_troops_survived json not null default '{}',
  resources_stolen         json not null default '{}',

  attacker_attack_power    int not null default 0,
  defender_defence_power   int not null default 0,

  attacker_read            boolean not null default false,
  defender_read            boolean not null default false,
  attacker_deleted         boolean not null default false,
  defender_deleted         boolean not null default false
);

create index idx_reports_attacker on battle_reports(attacker_player_id, fought_at desc);
create index idx_reports_defender on battle_reports(defender_player_id, fought_at desc);
create index idx_reports_atk_city on battle_reports(attacker_city_id);
create index idx_reports_def_city on battle_reports(defender_city_id);
