-- (H2-compatible) type-based combat: seeded unit catalog + split defence.

create table unit_types (
  id                    bigint generated by default as identity primary key,
  name                  varchar(32) not null unique,
  attack_type           varchar(16) not null,
  attack                int not null default 0,
  defense_blunt         int not null default 0,
  defense_sharp         int not null default 0,
  defense_distance      int not null default 0,
  speed_minutes_per_tile int not null default 20,
  carry_capacity        int not null default 0,
  population_cost       int not null default 1,
  kind                  varchar(8)  not null default 'LAND',
  from_queue            varchar(16) not null default 'BARRACKS',
  train_seconds         int not null default 15,
  cost_wood             int not null default 0,
  cost_stone            int not null default 0,
  cost_silver           int not null default 0,
  research_required     varchar(32)
);

insert into unit_types
  (name, attack_type, attack, defense_blunt, defense_sharp, defense_distance,
   speed_minutes_per_tile, carry_capacity, population_cost, kind, from_queue, train_seconds,
   cost_wood, cost_stone, cost_silver, research_required) values
  ('HOPLITE',  'BLUNT',    16, 80, 50, 40, 30, 10, 1, 'LAND', 'BARRACKS', 15,  60,  30,  30, null),
  ('SWORDSMAN','BLUNT',    55, 45, 25, 20, 22, 20, 1, 'LAND', 'BARRACKS', 18,  80,  40,  30, null),
  ('SPEARMAN', 'SHARP',    50, 30, 75, 35, 22, 25, 1, 'LAND', 'BARRACKS', 18,  70,  50,  30, null),
  ('ARCHER',   'DISTANCE', 60, 25, 40, 70, 18, 30, 1, 'LAND', 'BARRACKS', 20,  80,  30,  60, null),
  ('HORSEMAN', 'SHARP',   110, 30, 25, 35, 12, 80, 4, 'LAND', 'BARRACKS', 40, 160, 100, 140, null),
  ('CATAPULT', 'SIEGE',   200, 20, 20, 20, 60, 30, 8, 'LAND', 'BARRACKS', 60, 380, 520, 220, 'CATAPULT');

-- Old units no longer exist. Clear stale references.
delete from build_jobs where unit_type is not null;
delete from movements where resolved = false;
truncate table city_units;
